project_id = "rczygmsaybzcrmdxxyge"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_anonymous_sign_ins = false

[functions.create-pix-payment]
verify_jwt = true

[functions.secure-pix-webhook]
verify_jwt = false

[functions.asaas-subaccount-manager]
verify_jwt = true

[functions.asaas-split-manager]
verify_jwt = false

[functions.process-real-payment]
verify_jwt = true

[functions.add-user-credits]
verify_jwt = true

[functions.confirm-mlm-payment]
verify_jwt = false

[functions.daily-credit-conversion]
verify_jwt = false

[functions.daily-trigger-check]
verify_jwt = false

[functions.log-activity]
verify_jwt = true

[functions.log-error]
verify_jwt = false

[functions.mark-payment-paid]
verify_jwt = true

[functions.notification-triggers]
verify_jwt = false

[functions.process-mlm-purchase]
verify_jwt = true

[functions.process-payment]
verify_jwt = true

[functions.release-professional-payment]
verify_jwt = true

[functions.request-withdrawal]
verify_jwt = true

[functions.send-contemplation-email]
verify_jwt = false

[functions.send-email-sendgrid]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-payment-notification]
verify_jwt = false

[functions.send-voucher]
verify_jwt = false

[functions.stripe-account-status]
verify_jwt = true

[functions.stripe-create-checkout]
verify_jwt = true

[functions.stripe-onboard]
verify_jwt = true

[functions.upload-secure-file]
verify_jwt = true

[functions.use-user-credits]
verify_jwt = true