name: Mirror to amigo-do-grupo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Push to amigo-do-grupo
        run: |
          git config user.name "juninhoatituderezende-cmd"
          git config user.email "juninhoatitude@gmail.com"
          git remote remove mirror || true
          git remote add mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/americano10/amigo-do-grupo.git
          git push mirror main --force
