name: Mirror to amigo-do-grupo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Push to amigo-do-grupo
        env:
          MIRROR_URL: https://x-access-token:${{ secrets.GH_PAT }}@github.com/americano10/amigo-do-grupo.git
        run: |
          git config user.name "juninhoatituderezende-cmd"
          git config user.email "juninhoatitude@gmail.com"
          git remote remove mirror || true
          git remote add mirror "$MIRROR_URL"
          git push mirror main --force
          # Se quiser espelhar também as tags:
          # git push mirror --tags --force
