name: Mirror to Lovable

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

    - name: Push changes to Lovable
      run: |
        git config --global user.name "juninhoatituderezende-cmd"
        git config --global user.email "juninhoatitude@gmail.com"
        git remote add lovable https://x-access-token:${{ secrets.ACCESS_TOKEN_MIRROR }}@github.com/SEU-USUARIO/SEU-REPOSITORIO-DESTINO.git
        git push lovable main --force
