name: Mirror to Lovable

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Push to Lovable
        run: |
          git config user.name "juninhoatituderezende-cmd"
          git config user.email "juninhoatitude@gmail.com"
          git remote remove mirror || true
          git remote add mirror https://x-access-token:${{ secrets.ACCESS_TOKEN_MIRROR }}@github.com/cursoragent/amigo-do-peito.git
          git push mirror main --force
